(()=>{
const BASE='app6i45G4WG2nmQff',TABLE='Messagerie interne';
const channel=new BroadcastChannel('gcos-comms-v2');
const staff=['David','Bénédicte','Séverine','Apprenti'];
function currentUser(){try{const s=JSON.parse(sessionStorage.getItem('jarvis-session')||'null');const a=JSON.parse(localStorage.getItem('jarvis-accounts')||'[]');return a.find(x=>x.id===s?.id)||{name:'Utilisateur',id:'inconnu'}}catch{return{name:'Utilisateur',id:'inconnu'}}}
function speak(text){try{const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';speechSynthesis.cancel();speechSynthesis.speak(u)}catch{}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function injectStyle(){if(document.getElementById('gcos-v5-style'))return;const s=document.createElement('style');s.id='gcos-v5-style';s.textContent=`
.gcos-modal{position:fixed;inset:0;z-index:20000;background:#04090deF;display:grid;place-items:center;padding:18px}.gcos-box{width:min(680px,100%);max-height:90vh;overflow:auto;background:linear-gradient(145deg,#102936,#09151c);color:#fff;border:1px solid #3d7280;border-radius:22px;padding:20px;box-shadow:0 25px 80px #000}.gcos-box h2{margin-top:0}.gcos-box input,.gcos-box textarea,.gcos-box select{width:100%;padding:12px;margin:7px 0 13px;border-radius:12px;border:1px solid #355b66;background:#061218;color:#fff}.gcos-row{display:flex;gap:10px;flex-wrap:wrap}.gcos-btn{border:1px solid #416a75;border-radius:12px;padding:11px 15px;background:#173641;color:#fff;font-weight:800;cursor:pointer}.gcos-primary{background:linear-gradient(90deg,#8fe6ff,#83c968);color:#071116;border:0}.gcos-danger{background:#bd1515;border-color:#ff5a5a}.gcos-recipient{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.gcos-recipient button{padding:16px}.gcos-toast{position:fixed;right:18px;bottom:110px;z-index:21000;background:#102936;color:#fff;border:1px solid #58cce8;border-radius:14px;padding:14px 18px;box-shadow:0 15px 50px #000}.gcos-emergency{position:fixed;inset:0;z-index:30000;background:#8c0000;color:#fff;display:grid;place-items:center;text-align:center;padding:25px;animation:gcosFlash .38s infinite alternate}.gcos-emergency h1{font-size:clamp(2rem,7vw,6rem);margin:.2em}.gcos-emergency .icon{font-size:clamp(5rem,15vw,12rem)}@keyframes gcosFlash{to{background:#ff1717;filter:brightness(1.25)}}
#jarvisGlobalButton{position:fixed;left:18px;bottom:84px;z-index:15000;display:flex;align-items:center;gap:11px;border:1px solid #70e5ff88;border-radius:24px;padding:11px 15px 11px 11px;background:linear-gradient(135deg,#071c2aF2,#123848F2);color:#fff;box-shadow:0 0 35px #26cfff55,0 18px 45px #0008;cursor:pointer}.jarvis-core{display:grid;place-items:center;width:52px;height:52px;border-radius:50%;font-weight:1000;font-size:1.45rem;background:radial-gradient(circle,#fff 0 9%,#58e0ff 11% 24%,#087ba3 28% 52%,#04131e 55%);box-shadow:0 0 18px #63e6ff,0 0 42px #18bde9;animation:jp 2s infinite}.jarvis-label{display:flex;flex-direction:column;text-align:left}.jarvis-label b{letter-spacing:.14em}.jarvis-label small{color:#b8efff}.stat{cursor:pointer;transition:.18s}.stat:hover{transform:translateY(-2px);box-shadow:0 0 0 1px #66dffb inset,0 12px 32px #0007}@keyframes jp{50%{transform:scale(1.06)}}@media(max-width:650px){.gcos-recipient{grid-template-columns:1fr}#jarvisGlobalButton{bottom:82px;border-radius:50%;padding:10px}.jarvis-label{display:none}}
`;document.head.appendChild(s)}
function modal(html){injectStyle();const d=document.createElement('div');d.className='gcos-modal';d.innerHTML='<div class="gcos-box">'+html+'</div>';document.body.appendChild(d);return d}
function toast(text){injectStyle();const d=document.createElement('div');d.className='gcos-toast';d.textContent=text;document.body.appendChild(d);setTimeout(()=>d.remove(),2800)}
function airtableToken(){return localStorage.getItem('gcos_airtable_pat')||''}
async function saveAirtable(fields){const token=airtableToken();if(!token)return false;try{const r=await fetch('https://api.airtable.com/v0/'+BASE+'/'+encodeURIComponent(TABLE),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({records:[{fields}],typecast:true})});return r.ok}catch{return false}}
async function publish(type,priority,recipients,content){const u=currentUser(),now=new Date().toISOString();const msg={'Message':type+' '+now,'Date et heure':now,'Expéditeur':u.name,'Destinataires':recipients,'Type':type,'Priorité':priority,'Question / contenu':content,'Statut':'Nouveau','Niveau de confidentialité':'Interne','Origine':'GCOS','Lu par l’employé':false,'Lu par la direction':false};channel.postMessage(msg);localStorage.setItem('gcos-last-message',JSON.stringify(msg));const queue=JSON.parse(localStorage.getItem('gcos-message-queue')||'[]');queue.push(msg);localStorage.setItem('gcos-message-queue',JSON.stringify(queue.slice(-100)));await saveAirtable(msg);return msg}
function message(){const d=modal('<h2>💬 Contacter le personnel</h2><label>Destinataire</label><select id="to"><option value="">Choisir…</option>'+staff.map(x=>'<option>'+x+'</option>').join('')+'<option>Tout le personnel</option></select><label>Message</label><textarea id="txt" rows="5" placeholder="Votre message…"></textarea><div class="gcos-row"><button class="gcos-btn gcos-primary" id="send">Envoyer</button><button class="gcos-btn" id="close">Fermer</button></div>');d.querySelector('#send').onclick=async()=>{const to=d.querySelector('#to').value,txt=d.querySelector('#txt').value.trim();if(!to||!txt)return toast('Choisissez un destinataire et saisissez le message.');const recipients=to==='Tout le personnel'?staff:[to];await publish('Message','Normale',recipients,txt);d.remove();toast('Message envoyé à '+to+'.');speak('Message envoyé à '+to+'.')};d.querySelector('#close').onclick=()=>d.remove()}
function assistance(){const d=modal('<h2>🟠 Demande d’assistance</h2><p>Choisissez la personne à prévenir. Elle seule recevra la demande.</p><div class="gcos-recipient">'+staff.filter(x=>x!==currentUser().name).map(x=>'<button class="gcos-btn" data-name="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><label>Besoin d’aide</label><textarea id="reason" rows="4" placeholder="Expliquez brièvement le besoin…"></textarea><div class="gcos-row"><button class="gcos-btn" id="close">Annuler</button></div>');d.querySelectorAll('[data-name]').forEach(b=>b.onclick=async()=>{const name=b.dataset.name,reason=d.querySelector('#reason').value.trim()||'Assistance demandée.';await publish('Assistance','Haute',[name],reason);d.remove();toast(name+' a été prévenu(e).');speak(name+' a été prévenu.')});d.querySelector('#close').onclick=()=>d.remove()}
function siren(){try{const A=window.AudioContext||window.webkitAudioContext,c=new A();for(let i=0;i<18;i++){const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.16;o.type='square';o.frequency.setValueAtTime(i%2?620:920,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.22,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.15)}setTimeout(()=>c.close(),3400)}catch{}}
async function emergency(){injectStyle();const u=currentUser(),text='URGENCE GÉNÉRALE déclenchée par '+u.name+' à '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});siren();await publish('Urgence','Critique',staff,text);localStorage.setItem('gcos-priority-alert',JSON.stringify({id:Date.now(),message:text,at:new Date().toISOString()}));const e=document.createElement('div');e.className='gcos-emergency';e.innerHTML='<div><div class="icon">🚨</div><h1>URGENCE</h1><p>'+esc(text)+'</p><p>Tout le personnel a été alerté.</p><div class="gcos-row" style="justify-content:center"><a class="gcos-btn gcos-primary" href="tel:112">Appeler le 112</a><button class="gcos-btn" id="ack">J’ai pris connaissance</button></div></div>';document.body.appendChild(e);e.querySelector('#ack').onclick=()=>e.remove();try{window.open('mailto:gentlecar64@gmail.com,bene.lopez1976@gmail.com?subject='+encodeURIComponent('URGENCE GCOS')+'&body='+encodeURIComponent(text),'_blank')}catch{}}
function receive(m){const u=currentUser();const recipients=Array.isArray(m.Destinataires)?m.Destinataires:[m.Destinataires];if(!recipients.includes(u.name)&&!recipients.includes('Tout le personnel'))return;if(m.Type==='Urgence'){siren();const e=document.createElement('div');e.className='gcos-emergency';e.innerHTML='<div><div class="icon">🚨</div><h1>URGENCE</h1><p>'+esc(m['Question / contenu'])+'</p><button class="gcos-btn" id="ack">J’ai pris connaissance</button></div>';document.body.appendChild(e);e.querySelector('#ack').onclick=()=>e.remove()}else{toast((m.Type==='Assistance'?'Assistance demandée par ':'Message de ')+(m.Expéditeur||'GCOS')+' : '+(m['Question / contenu']||''));speak((m.Type==='Assistance'?'Assistance demandée. ':'Nouveau message. ')+(m['Question / contenu']||''))}}
channel.onmessage=e=>receive(e.data);
function installJarvis(){injectStyle();if(document.getElementById('jarvisGlobalButton'))return;const b=document.createElement('button');b.id='jarvisGlobalButton';b.innerHTML='<span class="jarvis-core">J</span><span class="jarvis-label"><b>JARVIS</b><small>Parler maintenant</small></span>';b.onclick=()=>location.href='jarvis.html';document.body.appendChild(b)}
function activateControlRoom(){document.querySelectorAll('.stat').forEach(card=>{const label=(card.querySelector('.muted')?.textContent||'').toLowerCase();card.setAttribute('role','button');card.tabIndex=0;const open=()=>{if(label.includes('intervention'))location.href='planning.html';else if(label.includes('devis'))location.href='gestion.html#devis';else if(label.includes('commande'))location.href='gestion.html#commandes';else if(label.includes('facturer'))location.href='gestion.html#facturation'};card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')open()}})}
function install(){injectStyle();installJarvis();activateControlRoom()}
window.GCOSComms={message,assistance,emergency};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();